typography_spectrum: 0.19271
color:
  brandColors:
    - '#000000'
    - '#3a4d87'
    - '#d02500'
    - '#fefe4b'
    - '#fb9200'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.1875
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: Youth on Fire
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Youth on Fire
description: Ignite Induce Inspire
purpose: []
