name: Youth on Fire
favicon: null
layout_spectrum: 1
typography_spectrum: 0.19271
title: Youth on Fire
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#3a4d87'
    - '#d02500'
    - '#fefe4b'
    - '#fb9200'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
