name: Youth on Fire
favicon: null
layout_spectrum: 0.4368554870598018
typography_spectrum: 0.4654559299815446
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.36459844605997205
  lightness: 0.3469114303588867
  saturation: 0.16195480548776686
  rhythmicContrast: 0.2542729517444968
purpose: []
